name: 'Deploy Node.js to Docker'
description: 'Build and run a Node.js app in a Docker container'
author: 'Your Name'

inputs:
  port:
    description: 'Port to expose'
    required: false
    default: '3000'
  container-name:
    description: 'Docker container name'
    required: false
    default: 'nodejs-app'
  image-name:
    description: 'Docker image name'
    required: false
    default: 'my-nodejs-app'

runs:
  using: 'composite'
  steps:
    - name: Build Docker Image
      shell: bash
      run: |
        docker build -t ${{ inputs.image-name }} .

    - name: Stop & Remove Old Container
      shell: bash
      run: |
        docker stop ${{ inputs.container-name }} 2>/dev/null || true
        docker rm ${{ inputs.container-name }} 2>/dev/null || true

    - name: Run New Container
      shell: bash
      run: |
        docker run -d \
          --name ${{ inputs.container-name }} \
          -p ${{ inputs.port }}:3000 \
          ${{ inputs.image-name }}

    - name: Show Deployment Info
      shell: bash
      run: |
        echo "App is running at http://localhost:${{ inputs.port }}"
        docker ps --filter "name=${{ inputs.container-name }}"
        docker logs ${{ inputs.container-name }} --tail 10
